CREATE DATABASE ESTUDOS_01

CREATE TABLE [ESTADOS]
([ID_ESTADO] [CHAR] (2) NOT NULL,
[NOME] [VARCHAR] (50) NOT NULL,
CONSTRAINT PK_ID_ESTADO
PRIMARY KEY CLUSTERED ([ID_ESTADO])
);

SELECT * FROM ESTADOS;

CREATE TABLE [CIDADES]
([ID_CIDADE] [CHAR] (2) NOT NULL,
[NOME] [VARCHAR] (100) NOT NULL,
[ESTADO] [CHAR] (2) NOT NULL,
CONSTRAINT PK_ID_CIDADE
PRIMARY KEY CLUSTERED ([ID_CIDADE])
);

ALTER TABLE [CIDADES]
DROP CONSTRAINT PK_ID_CIDADE

ALTER TABLE [CIDADES]
ALTER COLUMN [ID_CIDADE] [SMALLINT] NOT NULL;

ALTER TABLE [CIDADES]
ADD CONSTRAINT PK_ID_CIDADE PRIMARY KEY CLUSTERED ([ID_CIDADE])

SELECT * FROM CIDADES;

ALTER TABLE CIDADES
ADD CONSTRAINT FK_ID_ESTADO
FOREIGN KEY ([ESTADO]) REFERENCES ESTADOS([ID_ESTADO]);

INSERT INTO [ESTADOS]
( NOME, [ID_ESTADO])
VALUES
('Acre','AC'),
('Alagoas','AL'),
('Amapá','AP'),
('Amazonas','AM'),
('Bahia','BA'),
('Ceará', 'CE'),
('Espírito Santo','ES'),
('Goiás','GO'),
('Maranhão','MA'),
('Mato Grosso','MT'),
('Mato Grosso do Sul','MS'),
('Minas Gerais','MG'),
('Pará','PA'),
('Paraíba','PB'),
('Paraná','PR'),
('Pernambuco','PE'),
('Piauí','PI'),
('Rio de Janeiro','RJ'),
('Rio Grande do Norte','RN'),
('Rio Grande do Sul','RS'),
('Rondônia','RO'),
('Roraima','RR'),
('Santa Catarina','SC'),
('São Paulo','SP'),
('Sergipe','SE'),
('Tocantins','TO'),
('Distrito Federal','DF');

INSERT INTO [CIDADES]
Values
(001, 'Acrelândia', 'AC'),
(002, 'Assis Brasil', 'AC'),
(003, 'Rio Branco','AC'),
(004, 'Maceió', 'AL'),
(005, 'Arapiraca','AL'),
(045, 'Curitiba', 'PR'),
(046, 'Londrina', 'PR'),
(047, 'Londrina', 'PR'),
(054, 'Angra dos Reis', 'RJ'),
(055, 'Niterói', 'RJ'),
(056, 'Rio de Janeiro', 'RJ'),
(072, 'São Paulo', 'SP'),
(073, 'Guarulhos', 'SP'),
(074, 'São José dos Campos', 'SP')

--TESTE FOREIGN KEY

--INSERT INTO [CIDADES]
--VALUES
--(075, 'Aracaju', 'xx')

--INSERT INTO [ESTADOS]
--VALUES
--('ZN', 'ZONA NORTE')

--DELETE FROM [ESTADOS] WHERE [ID_ESTADO] = 'ZN'

--EXIBE TODOS OS ESTADOS E CIDADES CORRESPONDENTES. QUANDO NÃO HÁ CIDADE CADASTRADA, IMPRIME NULL
SELECT A.ID_ESTADO, B.NOME FROM ESTADOS A LEFT JOIN CIDADES B ON A.ID_ESTADO = B.ESTADO

--IGUAL O ANTERIOR, PORÉM, QUANDO É NULL IMPRIME NDA
SELECT A.ID_ESTADO,
CASE
	WHEN B.NOME IS NULL THEN'NDA'
	ELSE B.NOME
END
FROM ESTADOS A LEFT JOIN CIDADES B ON A.ID_ESTADO = B.ESTADO

--RETORNA QUANTIDADE DE CIDADES DE CADA ESTADO
SELECT ESTADO, COUNT(*) [CIDADES POR ESTADO] FROM CIDADES GROUP BY ESTADO


--RETORNA QUANTIDADE DE CIDADES DE CADA ESTADO 2
SELECT ESTADOS.ID_ESTADO, ISNULL (COUNT(CIDADES.NOME), 0) [CIDADES POR ESTADO]
FROM ESTADOS LEFT JOIN CIDADES 
ON ESTADOS.ID_ESTADO = CIDADES.ESTADO 
GROUP BY CIDADES.ESTADO, ESTADOS.ID_ESTADO

--RETORNA QUANTIDADE DE CIDADES DE CADA ESTADO 3
SELECT A.ID_ESTADO, COUNT(B.NOME) [CIDADES POR ESTADO]
FROM ESTADOS A LEFT JOIN CIDADES B 
ON A.ID_ESTADO = B.ESTADO 
GROUP BY B.ESTADO, A.ID_ESTADO

